[theme]
base = "dark"
primaryColor = "#4CAF50"           # green accent (matches pollutant cards)
backgroundColor = "#121212"        # same as CSS background
secondaryBackgroundColor = "#1c1c1c"
textColor = "#f5f5f5"
font = "sans serif"

[server]
headless = true
enableCORS = false
